apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-kafka-connect-headless
  namespace: ingestion
spec:
  clusterIP: None 
  selector:
    app: edh-connect-cluster
    release: ingestion
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
