apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-schema-registry-headless
  namespace: confluent
spec:
  clusterIP: None 
  selector:
    app: cp-schema-registry
    release: confluent
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
