apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: confluent
spec:
  selector:
    app: cp-control-center 
  ports:
    - port: 8080
      targetPort: 9021
      #nodePort: 9021
  type: LoadBalancer